// Code generated by MockGen. DO NOT EDIT.
// Source: ./package/service (interfaces: AccessControlService,ContestService,UserService,TaskService,AuthService,GroupService,SubmissionService,LanguageService,JWTService,QueueService,WorkerService)
//
// Generated by this command:
//
//	mockgen -destination package/service/mocks/mockgen.go ./package/service AccessControlService,ContestService,UserService,TaskService,AuthService,GroupService,SubmissionService,LanguageService,JWTService,QueueService,WorkerService
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	sync "sync"

	database "github.com/mini-maxit/backend/internal/database"
	schemas "github.com/mini-maxit/backend/package/domain/schemas"
	types "github.com/mini-maxit/backend/package/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAccessControlService is a mock of AccessControlService interface.
type MockAccessControlService struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControlServiceMockRecorder
	isgomock struct{}
}

// MockAccessControlServiceMockRecorder is the mock recorder for MockAccessControlService.
type MockAccessControlServiceMockRecorder struct {
	mock *MockAccessControlService
}

// NewMockAccessControlService creates a new mock instance.
func NewMockAccessControlService(ctrl *gomock.Controller) *MockAccessControlService {
	mock := &MockAccessControlService{ctrl: ctrl}
	mock.recorder = &MockAccessControlServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessControlService) EXPECT() *MockAccessControlServiceMockRecorder {
	return m.recorder
}

// AddCollaborator mocks base method.
func (m *MockAccessControlService) AddCollaborator(db database.Database, currentUser *schemas.User, resourceType types.ResourceType, resourceID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollaborator", db, currentUser, resourceType, resourceID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCollaborator indicates an expected call of AddCollaborator.
func (mr *MockAccessControlServiceMockRecorder) AddCollaborator(db, currentUser, resourceType, resourceID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollaborator", reflect.TypeOf((*MockAccessControlService)(nil).AddCollaborator), db, currentUser, resourceType, resourceID, userID, permission)
}

// CanUserAccess mocks base method.
func (m *MockAccessControlService) CanUserAccess(db database.Database, resourceType types.ResourceType, resourceID int64, user *schemas.User, requiredPermission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanUserAccess", db, resourceType, resourceID, user, requiredPermission)
	ret0, _ := ret[0].(error)
	return ret0
}

// CanUserAccess indicates an expected call of CanUserAccess.
func (mr *MockAccessControlServiceMockRecorder) CanUserAccess(db, resourceType, resourceID, user, requiredPermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanUserAccess", reflect.TypeOf((*MockAccessControlService)(nil).CanUserAccess), db, resourceType, resourceID, user, requiredPermission)
}

// GetAssignableUsers mocks base method.
func (m *MockAccessControlService) GetAssignableUsers(db database.Database, currentUser *schemas.User, resourceType types.ResourceType, resourceID int64, params schemas.PaginationParams) (*schemas.PaginatedResult[[]schemas.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignableUsers", db, currentUser, resourceType, resourceID, params)
	ret0, _ := ret[0].(*schemas.PaginatedResult[[]schemas.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignableUsers indicates an expected call of GetAssignableUsers.
func (mr *MockAccessControlServiceMockRecorder) GetAssignableUsers(db, currentUser, resourceType, resourceID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignableUsers", reflect.TypeOf((*MockAccessControlService)(nil).GetAssignableUsers), db, currentUser, resourceType, resourceID, params)
}

// GetCollaborators mocks base method.
func (m *MockAccessControlService) GetCollaborators(db database.Database, currentUser *schemas.User, resourceType types.ResourceType, resourceID int64) ([]schemas.Collaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollaborators", db, currentUser, resourceType, resourceID)
	ret0, _ := ret[0].([]schemas.Collaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollaborators indicates an expected call of GetCollaborators.
func (mr *MockAccessControlServiceMockRecorder) GetCollaborators(db, currentUser, resourceType, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollaborators", reflect.TypeOf((*MockAccessControlService)(nil).GetCollaborators), db, currentUser, resourceType, resourceID)
}

// GetUserPermission mocks base method.
func (m *MockAccessControlService) GetUserPermission(db database.Database, resourceType types.ResourceType, resourceID, userID int64) (types.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermission", db, resourceType, resourceID, userID)
	ret0, _ := ret[0].(types.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermission indicates an expected call of GetUserPermission.
func (mr *MockAccessControlServiceMockRecorder) GetUserPermission(db, resourceType, resourceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermission", reflect.TypeOf((*MockAccessControlService)(nil).GetUserPermission), db, resourceType, resourceID, userID)
}

// GrantOwnerAccess mocks base method.
func (m *MockAccessControlService) GrantOwnerAccess(db database.Database, resourceType types.ResourceType, resourceID, ownerID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantOwnerAccess", db, resourceType, resourceID, ownerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantOwnerAccess indicates an expected call of GrantOwnerAccess.
func (mr *MockAccessControlServiceMockRecorder) GrantOwnerAccess(db, resourceType, resourceID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantOwnerAccess", reflect.TypeOf((*MockAccessControlService)(nil).GrantOwnerAccess), db, resourceType, resourceID, ownerID)
}

// RemoveCollaborator mocks base method.
func (m *MockAccessControlService) RemoveCollaborator(db database.Database, currentUser *schemas.User, resourceType types.ResourceType, resourceID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCollaborator", db, currentUser, resourceType, resourceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCollaborator indicates an expected call of RemoveCollaborator.
func (mr *MockAccessControlServiceMockRecorder) RemoveCollaborator(db, currentUser, resourceType, resourceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCollaborator", reflect.TypeOf((*MockAccessControlService)(nil).RemoveCollaborator), db, currentUser, resourceType, resourceID, userID)
}

// UpdateCollaborator mocks base method.
func (m *MockAccessControlService) UpdateCollaborator(db database.Database, currentUser *schemas.User, resourceType types.ResourceType, resourceID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollaborator", db, currentUser, resourceType, resourceID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCollaborator indicates an expected call of UpdateCollaborator.
func (mr *MockAccessControlServiceMockRecorder) UpdateCollaborator(db, currentUser, resourceType, resourceID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollaborator", reflect.TypeOf((*MockAccessControlService)(nil).UpdateCollaborator), db, currentUser, resourceType, resourceID, userID, permission)
}

// MockContestService is a mock of ContestService interface.
type MockContestService struct {
	ctrl     *gomock.Controller
	recorder *MockContestServiceMockRecorder
	isgomock struct{}
}

// MockContestServiceMockRecorder is the mock recorder for MockContestService.
type MockContestServiceMockRecorder struct {
	mock *MockContestService
}

// NewMockContestService creates a new mock instance.
func NewMockContestService(ctrl *gomock.Controller) *MockContestService {
	mock := &MockContestService{ctrl: ctrl}
	mock.recorder = &MockContestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContestService) EXPECT() *MockContestServiceMockRecorder {
	return m.recorder
}

// AddGroupToContest mocks base method.
func (m *MockContestService) AddGroupToContest(db database.Database, currentUser *schemas.User, contestID, groupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroupToContest", db, currentUser, contestID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGroupToContest indicates an expected call of AddGroupToContest.
func (mr *MockContestServiceMockRecorder) AddGroupToContest(db, currentUser, contestID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroupToContest", reflect.TypeOf((*MockContestService)(nil).AddGroupToContest), db, currentUser, contestID, groupID)
}

// AddTaskToContest mocks base method.
func (m *MockContestService) AddTaskToContest(db database.Database, currentUser *schemas.User, contestID int64, request *schemas.AddTaskToContest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskToContest", db, currentUser, contestID, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTaskToContest indicates an expected call of AddTaskToContest.
func (mr *MockContestServiceMockRecorder) AddTaskToContest(db, currentUser, contestID, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskToContest", reflect.TypeOf((*MockContestService)(nil).AddTaskToContest), db, currentUser, contestID, request)
}

// ApproveRegistrationRequest mocks base method.
func (m *MockContestService) ApproveRegistrationRequest(db database.Database, currentUser *schemas.User, contestID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveRegistrationRequest", db, currentUser, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveRegistrationRequest indicates an expected call of ApproveRegistrationRequest.
func (mr *MockContestServiceMockRecorder) ApproveRegistrationRequest(db, currentUser, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveRegistrationRequest", reflect.TypeOf((*MockContestService)(nil).ApproveRegistrationRequest), db, currentUser, contestID, userID)
}

// Create mocks base method.
func (m *MockContestService) Create(db database.Database, currentUser *schemas.User, contest *schemas.CreateContest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, currentUser, contest)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContestServiceMockRecorder) Create(db, currentUser, contest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContestService)(nil).Create), db, currentUser, contest)
}

// Delete mocks base method.
func (m *MockContestService) Delete(db database.Database, currentUser *schemas.User, contestID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, currentUser, contestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContestServiceMockRecorder) Delete(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContestService)(nil).Delete), db, currentUser, contestID)
}

// Edit mocks base method.
func (m *MockContestService) Edit(db database.Database, currentUser *schemas.User, contestID int64, editInfo *schemas.EditContest) (*schemas.CreatedContest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", db, currentUser, contestID, editInfo)
	ret0, _ := ret[0].(*schemas.CreatedContest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit indicates an expected call of Edit.
func (mr *MockContestServiceMockRecorder) Edit(db, currentUser, contestID, editInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockContestService)(nil).Edit), db, currentUser, contestID, editInfo)
}

// GetAllContests mocks base method.
func (m *MockContestService) GetAllContests(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.CreatedContest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContests", db, currentUser, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.CreatedContest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllContests indicates an expected call of GetAllContests.
func (mr *MockContestServiceMockRecorder) GetAllContests(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContests", reflect.TypeOf((*MockContestService)(nil).GetAllContests), db, currentUser, paginationParams)
}

// GetAssignableGroups mocks base method.
func (m *MockContestService) GetAssignableGroups(db database.Database, currentUser *schemas.User, contestID int64) ([]schemas.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignableGroups", db, currentUser, contestID)
	ret0, _ := ret[0].([]schemas.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignableGroups indicates an expected call of GetAssignableGroups.
func (mr *MockContestServiceMockRecorder) GetAssignableGroups(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignableGroups", reflect.TypeOf((*MockContestService)(nil).GetAssignableGroups), db, currentUser, contestID)
}

// GetAssignableTasks mocks base method.
func (m *MockContestService) GetAssignableTasks(db database.Database, currentUser *schemas.User, contestID int64) ([]schemas.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignableTasks", db, currentUser, contestID)
	ret0, _ := ret[0].([]schemas.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignableTasks indicates an expected call of GetAssignableTasks.
func (mr *MockContestServiceMockRecorder) GetAssignableTasks(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignableTasks", reflect.TypeOf((*MockContestService)(nil).GetAssignableTasks), db, currentUser, contestID)
}

// GetContestGroups mocks base method.
func (m *MockContestService) GetContestGroups(db database.Database, currentUser *schemas.User, contestID int64) ([]schemas.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestGroups", db, currentUser, contestID)
	ret0, _ := ret[0].([]schemas.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestGroups indicates an expected call of GetContestGroups.
func (mr *MockContestServiceMockRecorder) GetContestGroups(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestGroups", reflect.TypeOf((*MockContestService)(nil).GetContestGroups), db, currentUser, contestID)
}

// GetContestTask mocks base method.
func (m *MockContestService) GetContestTask(db database.Database, currentUser *schemas.User, contestID, taskID int64) (*schemas.TaskDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestTask", db, currentUser, contestID, taskID)
	ret0, _ := ret[0].(*schemas.TaskDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestTask indicates an expected call of GetContestTask.
func (mr *MockContestServiceMockRecorder) GetContestTask(db, currentUser, contestID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestTask", reflect.TypeOf((*MockContestService)(nil).GetContestTask), db, currentUser, contestID, taskID)
}

// GetContestsCreatedByUser mocks base method.
func (m *MockContestService) GetContestsCreatedByUser(db database.Database, userID int64, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.CreatedContest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestsCreatedByUser", db, userID, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.CreatedContest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestsCreatedByUser indicates an expected call of GetContestsCreatedByUser.
func (mr *MockContestServiceMockRecorder) GetContestsCreatedByUser(db, userID, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestsCreatedByUser", reflect.TypeOf((*MockContestService)(nil).GetContestsCreatedByUser), db, userID, paginationParams)
}

// GetDetailed mocks base method.
func (m *MockContestService) GetDetailed(db database.Database, currentUser *schemas.User, contestID int64) (*schemas.ContestDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetailed", db, currentUser, contestID)
	ret0, _ := ret[0].(*schemas.ContestDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetailed indicates an expected call of GetDetailed.
func (mr *MockContestServiceMockRecorder) GetDetailed(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetailed", reflect.TypeOf((*MockContestService)(nil).GetDetailed), db, currentUser, contestID)
}

// GetManagedContests mocks base method.
func (m *MockContestService) GetManagedContests(db database.Database, userID int64, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.ManagedContest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManagedContests", db, userID, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.ManagedContest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManagedContests indicates an expected call of GetManagedContests.
func (mr *MockContestServiceMockRecorder) GetManagedContests(db, userID, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManagedContests", reflect.TypeOf((*MockContestService)(nil).GetManagedContests), db, userID, paginationParams)
}

// GetMyContestResults mocks base method.
func (m *MockContestService) GetMyContestResults(db database.Database, currentUser *schemas.User, contestID int64) (*schemas.ContestResults, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyContestResults", db, currentUser, contestID)
	ret0, _ := ret[0].(*schemas.ContestResults)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyContestResults indicates an expected call of GetMyContestResults.
func (mr *MockContestServiceMockRecorder) GetMyContestResults(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyContestResults", reflect.TypeOf((*MockContestService)(nil).GetMyContestResults), db, currentUser, contestID)
}

// GetOngoingContests mocks base method.
func (m *MockContestService) GetOngoingContests(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.AvailableContest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOngoingContests", db, currentUser, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.AvailableContest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOngoingContests indicates an expected call of GetOngoingContests.
func (mr *MockContestServiceMockRecorder) GetOngoingContests(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOngoingContests", reflect.TypeOf((*MockContestService)(nil).GetOngoingContests), db, currentUser, paginationParams)
}

// GetPastContests mocks base method.
func (m *MockContestService) GetPastContests(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.AvailableContest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPastContests", db, currentUser, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.AvailableContest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPastContests indicates an expected call of GetPastContests.
func (mr *MockContestServiceMockRecorder) GetPastContests(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPastContests", reflect.TypeOf((*MockContestService)(nil).GetPastContests), db, currentUser, paginationParams)
}

// GetRegistrationRequests mocks base method.
func (m *MockContestService) GetRegistrationRequests(db database.Database, currentUser *schemas.User, contestID int64, statusFilter types.RegistrationRequestStatus) ([]schemas.RegistrationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationRequests", db, currentUser, contestID, statusFilter)
	ret0, _ := ret[0].([]schemas.RegistrationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationRequests indicates an expected call of GetRegistrationRequests.
func (mr *MockContestServiceMockRecorder) GetRegistrationRequests(db, currentUser, contestID, statusFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationRequests", reflect.TypeOf((*MockContestService)(nil).GetRegistrationRequests), db, currentUser, contestID, statusFilter)
}

// GetTaskContests mocks base method.
func (m *MockContestService) GetTaskContests(db database.Database, taskID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskContests", db, taskID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskContests indicates an expected call of GetTaskContests.
func (mr *MockContestServiceMockRecorder) GetTaskContests(db, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskContests", reflect.TypeOf((*MockContestService)(nil).GetTaskContests), db, taskID)
}

// GetTaskProgressForContest mocks base method.
func (m *MockContestService) GetTaskProgressForContest(db database.Database, currentUser *schemas.User, contestID int64) ([]schemas.TaskWithContestStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskProgressForContest", db, currentUser, contestID)
	ret0, _ := ret[0].([]schemas.TaskWithContestStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskProgressForContest indicates an expected call of GetTaskProgressForContest.
func (mr *MockContestServiceMockRecorder) GetTaskProgressForContest(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskProgressForContest", reflect.TypeOf((*MockContestService)(nil).GetTaskProgressForContest), db, currentUser, contestID)
}

// GetTasksForContest mocks base method.
func (m *MockContestService) GetTasksForContest(db database.Database, currentUser *schemas.User, contestID int64) ([]schemas.ContestTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasksForContest", db, currentUser, contestID)
	ret0, _ := ret[0].([]schemas.ContestTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasksForContest indicates an expected call of GetTasksForContest.
func (mr *MockContestServiceMockRecorder) GetTasksForContest(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasksForContest", reflect.TypeOf((*MockContestService)(nil).GetTasksForContest), db, currentUser, contestID)
}

// GetUpcomingContests mocks base method.
func (m *MockContestService) GetUpcomingContests(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.AvailableContest], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpcomingContests", db, currentUser, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.AvailableContest])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpcomingContests indicates an expected call of GetUpcomingContests.
func (mr *MockContestServiceMockRecorder) GetUpcomingContests(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpcomingContests", reflect.TypeOf((*MockContestService)(nil).GetUpcomingContests), db, currentUser, paginationParams)
}

// GetUserContests mocks base method.
func (m *MockContestService) GetUserContests(db database.Database, userID int64) (*schemas.UserContestsWithStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserContests", db, userID)
	ret0, _ := ret[0].(*schemas.UserContestsWithStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserContests indicates an expected call of GetUserContests.
func (mr *MockContestServiceMockRecorder) GetUserContests(db, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserContests", reflect.TypeOf((*MockContestService)(nil).GetUserContests), db, userID)
}

// GetVisibleTasksForContest mocks base method.
func (m *MockContestService) GetVisibleTasksForContest(db database.Database, currentUser *schemas.User, contestID int64, status types.ContestStatus) ([]schemas.ContestTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisibleTasksForContest", db, currentUser, contestID, status)
	ret0, _ := ret[0].([]schemas.ContestTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisibleTasksForContest indicates an expected call of GetVisibleTasksForContest.
func (mr *MockContestServiceMockRecorder) GetVisibleTasksForContest(db, currentUser, contestID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisibleTasksForContest", reflect.TypeOf((*MockContestService)(nil).GetVisibleTasksForContest), db, currentUser, contestID, status)
}

// IsTaskInContest mocks base method.
func (m *MockContestService) IsTaskInContest(db database.Database, contestID, taskID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTaskInContest", db, contestID, taskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTaskInContest indicates an expected call of IsTaskInContest.
func (mr *MockContestServiceMockRecorder) IsTaskInContest(db, contestID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTaskInContest", reflect.TypeOf((*MockContestService)(nil).IsTaskInContest), db, contestID, taskID)
}

// IsUserParticipant mocks base method.
func (m *MockContestService) IsUserParticipant(db database.Database, contestID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserParticipant", db, contestID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserParticipant indicates an expected call of IsUserParticipant.
func (mr *MockContestServiceMockRecorder) IsUserParticipant(db, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserParticipant", reflect.TypeOf((*MockContestService)(nil).IsUserParticipant), db, contestID, userID)
}

// RegisterForContest mocks base method.
func (m *MockContestService) RegisterForContest(db database.Database, currentUser *schemas.User, contestID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterForContest", db, currentUser, contestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterForContest indicates an expected call of RegisterForContest.
func (mr *MockContestServiceMockRecorder) RegisterForContest(db, currentUser, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterForContest", reflect.TypeOf((*MockContestService)(nil).RegisterForContest), db, currentUser, contestID)
}

// RejectRegistrationRequest mocks base method.
func (m *MockContestService) RejectRegistrationRequest(db database.Database, currentUser *schemas.User, contestID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectRegistrationRequest", db, currentUser, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectRegistrationRequest indicates an expected call of RejectRegistrationRequest.
func (mr *MockContestServiceMockRecorder) RejectRegistrationRequest(db, currentUser, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectRegistrationRequest", reflect.TypeOf((*MockContestService)(nil).RejectRegistrationRequest), db, currentUser, contestID, userID)
}

// RemoveGroupFromContest mocks base method.
func (m *MockContestService) RemoveGroupFromContest(db database.Database, currentUser *schemas.User, contestID, groupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGroupFromContest", db, currentUser, contestID, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGroupFromContest indicates an expected call of RemoveGroupFromContest.
func (mr *MockContestServiceMockRecorder) RemoveGroupFromContest(db, currentUser, contestID, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroupFromContest", reflect.TypeOf((*MockContestService)(nil).RemoveGroupFromContest), db, currentUser, contestID, groupID)
}

// ValidateContestSubmission mocks base method.
func (m *MockContestService) ValidateContestSubmission(db database.Database, contestID, taskID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateContestSubmission", db, contestID, taskID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateContestSubmission indicates an expected call of ValidateContestSubmission.
func (mr *MockContestServiceMockRecorder) ValidateContestSubmission(db, contestID, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateContestSubmission", reflect.TypeOf((*MockContestService)(nil).ValidateContestSubmission), db, contestID, taskID, userID)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserService) ChangePassword(db database.Database, currentUser schemas.User, userID int64, data *schemas.UserChangePassword) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", db, currentUser, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserServiceMockRecorder) ChangePassword(db, currentUser, userID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserService)(nil).ChangePassword), db, currentUser, userID, data)
}

// ChangeRole mocks base method.
func (m *MockUserService) ChangeRole(db database.Database, currentUser schemas.User, userID int64, role types.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeRole", db, currentUser, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeRole indicates an expected call of ChangeRole.
func (mr *MockUserServiceMockRecorder) ChangeRole(db, currentUser, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeRole", reflect.TypeOf((*MockUserService)(nil).ChangeRole), db, currentUser, userID, role)
}

// Edit mocks base method.
func (m *MockUserService) Edit(db database.Database, currentUser schemas.User, userID int64, updateInfo *schemas.UserEdit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", db, currentUser, userID, updateInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockUserServiceMockRecorder) Edit(db, currentUser, userID, updateInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockUserService)(nil).Edit), db, currentUser, userID, updateInfo)
}

// Get mocks base method.
func (m *MockUserService) Get(db database.Database, userID int64) (*schemas.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", db, userID)
	ret0, _ := ret[0].(*schemas.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserServiceMockRecorder) Get(db, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserService)(nil).Get), db, userID)
}

// GetAll mocks base method.
func (m *MockUserService) GetAll(db database.Database, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.User], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", db, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.User])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserServiceMockRecorder) GetAll(db, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserService)(nil).GetAll), db, paginationParams)
}

// GetByEmail mocks base method.
func (m *MockUserService) GetByEmail(db database.Database, email string) (*schemas.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", db, email)
	ret0, _ := ret[0].(*schemas.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserServiceMockRecorder) GetByEmail(db, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserService)(nil).GetByEmail), db, email)
}

// IsTaskAssignedToUser mocks base method.
func (m *MockUserService) IsTaskAssignedToUser(db database.Database, userID, taskID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTaskAssignedToUser", db, userID, taskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTaskAssignedToUser indicates an expected call of IsTaskAssignedToUser.
func (mr *MockUserServiceMockRecorder) IsTaskAssignedToUser(db, userID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTaskAssignedToUser", reflect.TypeOf((*MockUserService)(nil).IsTaskAssignedToUser), db, userID, taskID)
}

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
	isgomock struct{}
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskService) Create(db database.Database, currentUser *schemas.User, task *schemas.Task) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, currentUser, task)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskServiceMockRecorder) Create(db, currentUser, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskService)(nil).Create), db, currentUser, task)
}

// CreateTestCase mocks base method.
func (m *MockTaskService) CreateTestCase(db database.Database, taskID int64, archivePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTestCase", db, taskID, archivePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTestCase indicates an expected call of CreateTestCase.
func (mr *MockTaskServiceMockRecorder) CreateTestCase(db, taskID, archivePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTestCase", reflect.TypeOf((*MockTaskService)(nil).CreateTestCase), db, taskID, archivePath)
}

// Delete mocks base method.
func (m *MockTaskService) Delete(db database.Database, currentUser *schemas.User, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, currentUser, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTaskServiceMockRecorder) Delete(db, currentUser, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTaskService)(nil).Delete), db, currentUser, taskID)
}

// Edit mocks base method.
func (m *MockTaskService) Edit(db database.Database, currentUser *schemas.User, taskID int64, updateInfo *schemas.EditTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", db, currentUser, taskID, updateInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// Edit indicates an expected call of Edit.
func (mr *MockTaskServiceMockRecorder) Edit(db, currentUser, taskID, updateInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockTaskService)(nil).Edit), db, currentUser, taskID, updateInfo)
}

// Get mocks base method.
func (m *MockTaskService) Get(db database.Database, currentUser *schemas.User, taskID int64) (*schemas.TaskDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", db, currentUser, taskID)
	ret0, _ := ret[0].(*schemas.TaskDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskServiceMockRecorder) Get(db, currentUser, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskService)(nil).Get), db, currentUser, taskID)
}

// GetAll mocks base method.
func (m *MockTaskService) GetAll(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) ([]schemas.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", db, currentUser, paginationParams)
	ret0, _ := ret[0].([]schemas.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockTaskServiceMockRecorder) GetAll(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockTaskService)(nil).GetAll), db, currentUser, paginationParams)
}

// GetAllCreated mocks base method.
func (m *MockTaskService) GetAllCreated(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) (schemas.PaginatedResult[[]schemas.Task], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCreated", db, currentUser, paginationParams)
	ret0, _ := ret[0].(schemas.PaginatedResult[[]schemas.Task])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCreated indicates an expected call of GetAllCreated.
func (mr *MockTaskServiceMockRecorder) GetAllCreated(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCreated", reflect.TypeOf((*MockTaskService)(nil).GetAllCreated), db, currentUser, paginationParams)
}

// GetByTitle mocks base method.
func (m *MockTaskService) GetByTitle(db database.Database, title string) (*schemas.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTitle", db, title)
	ret0, _ := ret[0].(*schemas.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTitle indicates an expected call of GetByTitle.
func (mr *MockTaskServiceMockRecorder) GetByTitle(db, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTitle", reflect.TypeOf((*MockTaskService)(nil).GetByTitle), db, title)
}

// GetLimits mocks base method.
func (m *MockTaskService) GetLimits(db database.Database, currentUser *schemas.User, taskID int64) ([]schemas.TestCase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits", db, currentUser, taskID)
	ret0, _ := ret[0].([]schemas.TestCase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockTaskServiceMockRecorder) GetLimits(db, currentUser, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockTaskService)(nil).GetLimits), db, currentUser, taskID)
}

// GetMyLiveTasks mocks base method.
func (m *MockTaskService) GetMyLiveTasks(db database.Database, currentUser *schemas.User, paginationParams schemas.PaginationParams) (*schemas.MyTasksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyLiveTasks", db, currentUser, paginationParams)
	ret0, _ := ret[0].(*schemas.MyTasksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyLiveTasks indicates an expected call of GetMyLiveTasks.
func (mr *MockTaskServiceMockRecorder) GetMyLiveTasks(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyLiveTasks", reflect.TypeOf((*MockTaskService)(nil).GetMyLiveTasks), db, currentUser, paginationParams)
}

// ParseTestCase mocks base method.
func (m *MockTaskService) ParseTestCase(archivePath string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTestCase", archivePath)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTestCase indicates an expected call of ParseTestCase.
func (mr *MockTaskServiceMockRecorder) ParseTestCase(archivePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTestCase", reflect.TypeOf((*MockTaskService)(nil).ParseTestCase), archivePath)
}

// ProcessAndUpload mocks base method.
func (m *MockTaskService) ProcessAndUpload(db database.Database, currentUser *schemas.User, taskID int64, archivePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAndUpload", db, currentUser, taskID, archivePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessAndUpload indicates an expected call of ProcessAndUpload.
func (mr *MockTaskServiceMockRecorder) ProcessAndUpload(db, currentUser, taskID, archivePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAndUpload", reflect.TypeOf((*MockTaskService)(nil).ProcessAndUpload), db, currentUser, taskID, archivePath)
}

// PutLimits mocks base method.
func (m *MockTaskService) PutLimits(db database.Database, currentUser *schemas.User, taskID int64, limits schemas.PutTestCaseLimitsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutLimits", db, currentUser, taskID, limits)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutLimits indicates an expected call of PutLimits.
func (mr *MockTaskServiceMockRecorder) PutLimits(db, currentUser, taskID, limits any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutLimits", reflect.TypeOf((*MockTaskService)(nil).PutLimits), db, currentUser, taskID, limits)
}

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(db database.Database, userLogin schemas.UserLoginRequest) (*schemas.JWTTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", db, userLogin)
	ret0, _ := ret[0].(*schemas.JWTTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(db, userLogin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), db, userLogin)
}

// RefreshTokens mocks base method.
func (m *MockAuthService) RefreshTokens(db database.Database, refreshRequest schemas.RefreshTokenRequest) (*schemas.JWTTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", db, refreshRequest)
	ret0, _ := ret[0].(*schemas.JWTTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockAuthServiceMockRecorder) RefreshTokens(db, refreshRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockAuthService)(nil).RefreshTokens), db, refreshRequest)
}

// Register mocks base method.
func (m *MockAuthService) Register(db database.Database, userRegister schemas.UserRegisterRequest) (*schemas.JWTTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", db, userRegister)
	ret0, _ := ret[0].(*schemas.JWTTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(db, userRegister any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), db, userRegister)
}

// MockGroupService is a mock of GroupService interface.
type MockGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockGroupServiceMockRecorder
	isgomock struct{}
}

// MockGroupServiceMockRecorder is the mock recorder for MockGroupService.
type MockGroupServiceMockRecorder struct {
	mock *MockGroupService
}

// NewMockGroupService creates a new mock instance.
func NewMockGroupService(ctrl *gomock.Controller) *MockGroupService {
	mock := &MockGroupService{ctrl: ctrl}
	mock.recorder = &MockGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupService) EXPECT() *MockGroupServiceMockRecorder {
	return m.recorder
}

// AddUsers mocks base method.
func (m *MockGroupService) AddUsers(db database.Database, currentUser schemas.User, groupID int64, userIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsers", db, currentUser, groupID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUsers indicates an expected call of AddUsers.
func (mr *MockGroupServiceMockRecorder) AddUsers(db, currentUser, groupID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsers", reflect.TypeOf((*MockGroupService)(nil).AddUsers), db, currentUser, groupID, userIDs)
}

// Create mocks base method.
func (m *MockGroupService) Create(db database.Database, currentUser schemas.User, group *schemas.Group) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, currentUser, group)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGroupServiceMockRecorder) Create(db, currentUser, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGroupService)(nil).Create), db, currentUser, group)
}

// Delete mocks base method.
func (m *MockGroupService) Delete(db database.Database, currentUser schemas.User, groupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", db, currentUser, groupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGroupServiceMockRecorder) Delete(db, currentUser, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGroupService)(nil).Delete), db, currentUser, groupID)
}

// DeleteUsers mocks base method.
func (m *MockGroupService) DeleteUsers(db database.Database, currentUser schemas.User, groupID int64, userIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsers", db, currentUser, groupID, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUsers indicates an expected call of DeleteUsers.
func (mr *MockGroupServiceMockRecorder) DeleteUsers(db, currentUser, groupID, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsers", reflect.TypeOf((*MockGroupService)(nil).DeleteUsers), db, currentUser, groupID, userIDs)
}

// Edit mocks base method.
func (m *MockGroupService) Edit(db database.Database, currentUser schemas.User, groupID int64, editInfo *schemas.EditGroup) (*schemas.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", db, currentUser, groupID, editInfo)
	ret0, _ := ret[0].(*schemas.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit indicates an expected call of Edit.
func (mr *MockGroupServiceMockRecorder) Edit(db, currentUser, groupID, editInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockGroupService)(nil).Edit), db, currentUser, groupID, editInfo)
}

// Get mocks base method.
func (m *MockGroupService) Get(db database.Database, currentUser schemas.User, groupID int64) (*schemas.GroupDetailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", db, currentUser, groupID)
	ret0, _ := ret[0].(*schemas.GroupDetailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGroupServiceMockRecorder) Get(db, currentUser, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGroupService)(nil).Get), db, currentUser, groupID)
}

// GetAll mocks base method.
func (m *MockGroupService) GetAll(db database.Database, currentUser schemas.User, paginationParams schemas.PaginationParams) ([]schemas.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", db, currentUser, paginationParams)
	ret0, _ := ret[0].([]schemas.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockGroupServiceMockRecorder) GetAll(db, currentUser, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockGroupService)(nil).GetAll), db, currentUser, paginationParams)
}

// GetUsers mocks base method.
func (m *MockGroupService) GetUsers(db database.Database, currentUser schemas.User, groupID int64) ([]schemas.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", db, currentUser, groupID)
	ret0, _ := ret[0].([]schemas.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockGroupServiceMockRecorder) GetUsers(db, currentUser, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockGroupService)(nil).GetUsers), db, currentUser, groupID)
}

// MockSubmissionService is a mock of SubmissionService interface.
type MockSubmissionService struct {
	ctrl     *gomock.Controller
	recorder *MockSubmissionServiceMockRecorder
	isgomock struct{}
}

// MockSubmissionServiceMockRecorder is the mock recorder for MockSubmissionService.
type MockSubmissionServiceMockRecorder struct {
	mock *MockSubmissionService
}

// NewMockSubmissionService creates a new mock instance.
func NewMockSubmissionService(ctrl *gomock.Controller) *MockSubmissionService {
	mock := &MockSubmissionService{ctrl: ctrl}
	mock.recorder = &MockSubmissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubmissionService) EXPECT() *MockSubmissionServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubmissionService) Create(db database.Database, taskID, userID, languageID int64, contestID *int64, order int, fileID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", db, taskID, userID, languageID, contestID, order, fileID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubmissionServiceMockRecorder) Create(db, taskID, userID, languageID, contestID, order, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubmissionService)(nil).Create), db, taskID, userID, languageID, contestID, order, fileID)
}

// CreateSubmissionResult mocks base method.
func (m *MockSubmissionService) CreateSubmissionResult(db database.Database, submissionID int64, responseMessage schemas.QueueResponseMessage) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubmissionResult", db, submissionID, responseMessage)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubmissionResult indicates an expected call of CreateSubmissionResult.
func (mr *MockSubmissionServiceMockRecorder) CreateSubmissionResult(db, submissionID, responseMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubmissionResult", reflect.TypeOf((*MockSubmissionService)(nil).CreateSubmissionResult), db, submissionID, responseMessage)
}

// Get mocks base method.
func (m *MockSubmissionService) Get(db database.Database, submissionID int64, user *schemas.User) (schemas.Submission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", db, submissionID, user)
	ret0, _ := ret[0].(schemas.Submission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubmissionServiceMockRecorder) Get(db, submissionID, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubmissionService)(nil).Get), db, submissionID, user)
}

// GetAll mocks base method.
func (m *MockSubmissionService) GetAll(db database.Database, user *schemas.User, userID, taskID, contestID *int64, paginationParams schemas.PaginationParams) (*schemas.PaginatedResult[[]schemas.Submission], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", db, user, userID, taskID, contestID, paginationParams)
	ret0, _ := ret[0].(*schemas.PaginatedResult[[]schemas.Submission])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockSubmissionServiceMockRecorder) GetAll(db, user, userID, taskID, contestID, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockSubmissionService)(nil).GetAll), db, user, userID, taskID, contestID, paginationParams)
}

// GetAllForContest mocks base method.
func (m *MockSubmissionService) GetAllForContest(db database.Database, contestID int64, user *schemas.User, paginationParams schemas.PaginationParams) (*schemas.PaginatedResult[[]schemas.Submission], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForContest", db, contestID, user, paginationParams)
	ret0, _ := ret[0].(*schemas.PaginatedResult[[]schemas.Submission])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForContest indicates an expected call of GetAllForContest.
func (mr *MockSubmissionServiceMockRecorder) GetAllForContest(db, contestID, user, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForContest", reflect.TypeOf((*MockSubmissionService)(nil).GetAllForContest), db, contestID, user, paginationParams)
}

// GetAllForTask mocks base method.
func (m *MockSubmissionService) GetAllForTask(db database.Database, taskID int64, user *schemas.User, paginationParams schemas.PaginationParams) (*schemas.PaginatedResult[[]schemas.Submission], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForTask", db, taskID, user, paginationParams)
	ret0, _ := ret[0].(*schemas.PaginatedResult[[]schemas.Submission])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForTask indicates an expected call of GetAllForTask.
func (mr *MockSubmissionServiceMockRecorder) GetAllForTask(db, taskID, user, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForTask", reflect.TypeOf((*MockSubmissionService)(nil).GetAllForTask), db, taskID, user, paginationParams)
}

// GetAllForUser mocks base method.
func (m *MockSubmissionService) GetAllForUser(db database.Database, userID int64, user *schemas.User, paginationParams schemas.PaginationParams) (*schemas.PaginatedResult[[]schemas.Submission], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllForUser", db, userID, user, paginationParams)
	ret0, _ := ret[0].(*schemas.PaginatedResult[[]schemas.Submission])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllForUser indicates an expected call of GetAllForUser.
func (mr *MockSubmissionServiceMockRecorder) GetAllForUser(db, userID, user, paginationParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllForUser", reflect.TypeOf((*MockSubmissionService)(nil).GetAllForUser), db, userID, user, paginationParams)
}

// GetAvailableLanguages mocks base method.
func (m *MockSubmissionService) GetAvailableLanguages(db database.Database) ([]schemas.LanguageConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableLanguages", db)
	ret0, _ := ret[0].([]schemas.LanguageConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableLanguages indicates an expected call of GetAvailableLanguages.
func (mr *MockSubmissionServiceMockRecorder) GetAvailableLanguages(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableLanguages", reflect.TypeOf((*MockSubmissionService)(nil).GetAvailableLanguages), db)
}

// GetTaskStatsForContest mocks base method.
func (m *MockSubmissionService) GetTaskStatsForContest(db database.Database, user *schemas.User, contestID int64) ([]schemas.ContestTaskStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskStatsForContest", db, user, contestID)
	ret0, _ := ret[0].([]schemas.ContestTaskStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskStatsForContest indicates an expected call of GetTaskStatsForContest.
func (mr *MockSubmissionServiceMockRecorder) GetTaskStatsForContest(db, user, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskStatsForContest", reflect.TypeOf((*MockSubmissionService)(nil).GetTaskStatsForContest), db, user, contestID)
}

// GetUserStatsForContest mocks base method.
func (m *MockSubmissionService) GetUserStatsForContest(db database.Database, user *schemas.User, contestID int64, userID *int64) ([]schemas.UserContestStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatsForContest", db, user, contestID, userID)
	ret0, _ := ret[0].([]schemas.UserContestStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatsForContest indicates an expected call of GetUserStatsForContest.
func (mr *MockSubmissionServiceMockRecorder) GetUserStatsForContest(db, user, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatsForContest", reflect.TypeOf((*MockSubmissionService)(nil).GetUserStatsForContest), db, user, contestID, userID)
}

// GetUserStatsForContestTask mocks base method.
func (m *MockSubmissionService) GetUserStatsForContestTask(db database.Database, user *schemas.User, contestID, taskID int64) ([]schemas.TaskUserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatsForContestTask", db, user, contestID, taskID)
	ret0, _ := ret[0].([]schemas.TaskUserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatsForContestTask indicates an expected call of GetUserStatsForContestTask.
func (mr *MockSubmissionServiceMockRecorder) GetUserStatsForContestTask(db, user, contestID, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatsForContestTask", reflect.TypeOf((*MockSubmissionService)(nil).GetUserStatsForContestTask), db, user, contestID, taskID)
}

// MarkComplete mocks base method.
func (m *MockSubmissionService) MarkComplete(db database.Database, submissionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkComplete", db, submissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkComplete indicates an expected call of MarkComplete.
func (mr *MockSubmissionServiceMockRecorder) MarkComplete(db, submissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkComplete", reflect.TypeOf((*MockSubmissionService)(nil).MarkComplete), db, submissionID)
}

// MarkFailed mocks base method.
func (m *MockSubmissionService) MarkFailed(db database.Database, submissionID int64, errorMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", db, submissionID, errorMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockSubmissionServiceMockRecorder) MarkFailed(db, submissionID, errorMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockSubmissionService)(nil).MarkFailed), db, submissionID, errorMsg)
}

// MarkProcessing mocks base method.
func (m *MockSubmissionService) MarkProcessing(db database.Database, submissionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkProcessing", db, submissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkProcessing indicates an expected call of MarkProcessing.
func (mr *MockSubmissionServiceMockRecorder) MarkProcessing(db, submissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkProcessing", reflect.TypeOf((*MockSubmissionService)(nil).MarkProcessing), db, submissionID)
}

// Submit mocks base method.
func (m *MockSubmissionService) Submit(db database.Database, user *schemas.User, taskID, languageID int64, contestID *int64, submissionFilePath string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", db, user, taskID, languageID, contestID, submissionFilePath)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockSubmissionServiceMockRecorder) Submit(db, user, taskID, languageID, contestID, submissionFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockSubmissionService)(nil).Submit), db, user, taskID, languageID, contestID, submissionFilePath)
}

// MockLanguageService is a mock of LanguageService interface.
type MockLanguageService struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageServiceMockRecorder
	isgomock struct{}
}

// MockLanguageServiceMockRecorder is the mock recorder for MockLanguageService.
type MockLanguageServiceMockRecorder struct {
	mock *MockLanguageService
}

// NewMockLanguageService creates a new mock instance.
func NewMockLanguageService(ctrl *gomock.Controller) *MockLanguageService {
	mock := &MockLanguageService{ctrl: ctrl}
	mock.recorder = &MockLanguageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageService) EXPECT() *MockLanguageServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockLanguageService) GetAll(db database.Database) ([]schemas.LanguageConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", db)
	ret0, _ := ret[0].([]schemas.LanguageConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockLanguageServiceMockRecorder) GetAll(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockLanguageService)(nil).GetAll), db)
}

// GetAllEnabled mocks base method.
func (m *MockLanguageService) GetAllEnabled(db database.Database) ([]schemas.LanguageConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEnabled", db)
	ret0, _ := ret[0].([]schemas.LanguageConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEnabled indicates an expected call of GetAllEnabled.
func (mr *MockLanguageServiceMockRecorder) GetAllEnabled(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEnabled", reflect.TypeOf((*MockLanguageService)(nil).GetAllEnabled), db)
}

// Init mocks base method.
func (m *MockLanguageService) Init(db database.Database, enabledLanguages schemas.HandShakeResponsePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", db, enabledLanguages)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockLanguageServiceMockRecorder) Init(db, enabledLanguages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockLanguageService)(nil).Init), db, enabledLanguages)
}

// MockJWTService is a mock of JWTService interface.
type MockJWTService struct {
	ctrl     *gomock.Controller
	recorder *MockJWTServiceMockRecorder
	isgomock struct{}
}

// MockJWTServiceMockRecorder is the mock recorder for MockJWTService.
type MockJWTServiceMockRecorder struct {
	mock *MockJWTService
}

// NewMockJWTService creates a new mock instance.
func NewMockJWTService(ctrl *gomock.Controller) *MockJWTService {
	mock := &MockJWTService{ctrl: ctrl}
	mock.recorder = &MockJWTServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTService) EXPECT() *MockJWTServiceMockRecorder {
	return m.recorder
}

// AuthenticateToken mocks base method.
func (m *MockJWTService) AuthenticateToken(db database.Database, tokenString string) (*schemas.ValidateTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateToken", db, tokenString)
	ret0, _ := ret[0].(*schemas.ValidateTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateToken indicates an expected call of AuthenticateToken.
func (mr *MockJWTServiceMockRecorder) AuthenticateToken(db, tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateToken", reflect.TypeOf((*MockJWTService)(nil).AuthenticateToken), db, tokenString)
}

// GenerateTokens mocks base method.
func (m *MockJWTService) GenerateTokens(db database.Database, userId int64) (*schemas.JWTTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", db, userId)
	ret0, _ := ret[0].(*schemas.JWTTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockJWTServiceMockRecorder) GenerateTokens(db, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*MockJWTService)(nil).GenerateTokens), db, userId)
}

// RefreshTokens mocks base method.
func (m *MockJWTService) RefreshTokens(db database.Database, refreshToken string) (*schemas.JWTTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokens", db, refreshToken)
	ret0, _ := ret[0].(*schemas.JWTTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshTokens indicates an expected call of RefreshTokens.
func (mr *MockJWTServiceMockRecorder) RefreshTokens(db, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokens", reflect.TypeOf((*MockJWTService)(nil).RefreshTokens), db, refreshToken)
}

// MockQueueService is a mock of QueueService interface.
type MockQueueService struct {
	ctrl     *gomock.Controller
	recorder *MockQueueServiceMockRecorder
	isgomock struct{}
}

// MockQueueServiceMockRecorder is the mock recorder for MockQueueService.
type MockQueueServiceMockRecorder struct {
	mock *MockQueueService
}

// NewMockQueueService creates a new mock instance.
func NewMockQueueService(ctrl *gomock.Controller) *MockQueueService {
	mock := &MockQueueService{ctrl: ctrl}
	mock.recorder = &MockQueueServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueService) EXPECT() *MockQueueServiceMockRecorder {
	return m.recorder
}

// GetSubmissionID mocks base method.
func (m *MockQueueService) GetSubmissionID(db database.Database, messageID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubmissionID", db, messageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubmissionID indicates an expected call of GetSubmissionID.
func (mr *MockQueueServiceMockRecorder) GetSubmissionID(db, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubmissionID", reflect.TypeOf((*MockQueueService)(nil).GetSubmissionID), db, messageID)
}

// IsConnected mocks base method.
func (m *MockQueueService) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockQueueServiceMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockQueueService)(nil).IsConnected))
}

// LastWorkerStatus mocks base method.
func (m *MockQueueService) LastWorkerStatus() schemas.WorkersStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastWorkerStatus")
	ret0, _ := ret[0].(schemas.WorkersStatus)
	return ret0
}

// LastWorkerStatus indicates an expected call of LastWorkerStatus.
func (mr *MockQueueServiceMockRecorder) LastWorkerStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastWorkerStatus", reflect.TypeOf((*MockQueueService)(nil).LastWorkerStatus))
}

// PublishHandshake mocks base method.
func (m *MockQueueService) PublishHandshake() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishHandshake")
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishHandshake indicates an expected call of PublishHandshake.
func (mr *MockQueueServiceMockRecorder) PublishHandshake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishHandshake", reflect.TypeOf((*MockQueueService)(nil).PublishHandshake))
}

// PublishSubmission mocks base method.
func (m *MockQueueService) PublishSubmission(db database.Database, submissionID, submissionResultID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSubmission", db, submissionID, submissionResultID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSubmission indicates an expected call of PublishSubmission.
func (mr *MockQueueServiceMockRecorder) PublishSubmission(db, submissionID, submissionResultID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSubmission", reflect.TypeOf((*MockQueueService)(nil).PublishSubmission), db, submissionID, submissionResultID)
}

// PublishWorkerStatus mocks base method.
func (m *MockQueueService) PublishWorkerStatus() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWorkerStatus")
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWorkerStatus indicates an expected call of PublishWorkerStatus.
func (mr *MockQueueServiceMockRecorder) PublishWorkerStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWorkerStatus", reflect.TypeOf((*MockQueueService)(nil).PublishWorkerStatus))
}

// RetryPendingSubmissions mocks base method.
func (m *MockQueueService) RetryPendingSubmissions(db database.Database) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryPendingSubmissions", db)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryPendingSubmissions indicates an expected call of RetryPendingSubmissions.
func (mr *MockQueueServiceMockRecorder) RetryPendingSubmissions(db any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryPendingSubmissions", reflect.TypeOf((*MockQueueService)(nil).RetryPendingSubmissions), db)
}

// StatusCond mocks base method.
func (m *MockQueueService) StatusCond() *sync.Cond {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusCond")
	ret0, _ := ret[0].(*sync.Cond)
	return ret0
}

// StatusCond indicates an expected call of StatusCond.
func (mr *MockQueueServiceMockRecorder) StatusCond() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusCond", reflect.TypeOf((*MockQueueService)(nil).StatusCond))
}

// StatusMux mocks base method.
func (m *MockQueueService) StatusMux() *sync.Mutex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusMux")
	ret0, _ := ret[0].(*sync.Mutex)
	return ret0
}

// StatusMux indicates an expected call of StatusMux.
func (mr *MockQueueServiceMockRecorder) StatusMux() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusMux", reflect.TypeOf((*MockQueueService)(nil).StatusMux))
}

// UpdateWorkerStatus mocks base method.
func (m *MockQueueService) UpdateWorkerStatus(statusResponse schemas.StatusResponsePayload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkerStatus", statusResponse)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkerStatus indicates an expected call of UpdateWorkerStatus.
func (mr *MockQueueServiceMockRecorder) UpdateWorkerStatus(statusResponse any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkerStatus", reflect.TypeOf((*MockQueueService)(nil).UpdateWorkerStatus), statusResponse)
}

// MockWorkerService is a mock of WorkerService interface.
type MockWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerServiceMockRecorder
	isgomock struct{}
}

// MockWorkerServiceMockRecorder is the mock recorder for MockWorkerService.
type MockWorkerServiceMockRecorder struct {
	mock *MockWorkerService
}

// NewMockWorkerService creates a new mock instance.
func NewMockWorkerService(ctrl *gomock.Controller) *MockWorkerService {
	mock := &MockWorkerService{ctrl: ctrl}
	mock.recorder = &MockWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerService) EXPECT() *MockWorkerServiceMockRecorder {
	return m.recorder
}

// GetQueueStatus mocks base method.
func (m *MockWorkerService) GetQueueStatus(currentUser *schemas.User) (*schemas.QueueStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueStatus", currentUser)
	ret0, _ := ret[0].(*schemas.QueueStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueStatus indicates an expected call of GetQueueStatus.
func (mr *MockWorkerServiceMockRecorder) GetQueueStatus(currentUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueStatus", reflect.TypeOf((*MockWorkerService)(nil).GetQueueStatus), currentUser)
}

// GetStatus mocks base method.
func (m *MockWorkerService) GetStatus(currentUser *schemas.User) (*schemas.WorkersStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", currentUser)
	ret0, _ := ret[0].(*schemas.WorkersStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockWorkerServiceMockRecorder) GetStatus(currentUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockWorkerService)(nil).GetStatus), currentUser)
}

// ReconnectQueue mocks base method.
func (m *MockWorkerService) ReconnectQueue(currentUser *schemas.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconnectQueue", currentUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconnectQueue indicates an expected call of ReconnectQueue.
func (mr *MockWorkerServiceMockRecorder) ReconnectQueue(currentUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconnectQueue", reflect.TypeOf((*MockWorkerService)(nil).ReconnectQueue), currentUser)
}
