// Code generated by MockGen. DO NOT EDIT.
// Source: ./package/filestorage (interfaces: Decompressor,ArchiveValidator,ValidationRule,FileStorageService)
//
// Generated by this command:
//
//	mockgen -destination package/filestorage/mocks/mockgen.go ./package/filestorage Decompressor,ArchiveValidator,ValidationRule,FileStorageService
//

// Package mock_filestorage is a generated GoMock package.
package mock_filestorage

import (
	reflect "reflect"

	filestorage "github.com/mini-maxit/backend/package/filestorage"
	gomock "go.uber.org/mock/gomock"
)

// MockDecompressor is a mock of Decompressor interface.
type MockDecompressor struct {
	ctrl     *gomock.Controller
	recorder *MockDecompressorMockRecorder
	isgomock struct{}
}

// MockDecompressorMockRecorder is the mock recorder for MockDecompressor.
type MockDecompressorMockRecorder struct {
	mock *MockDecompressor
}

// NewMockDecompressor creates a new mock instance.
func NewMockDecompressor(ctrl *gomock.Controller) *MockDecompressor {
	mock := &MockDecompressor{ctrl: ctrl}
	mock.recorder = &MockDecompressorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecompressor) EXPECT() *MockDecompressorMockRecorder {
	return m.recorder
}

// DecompressArchive mocks base method.
func (m *MockDecompressor) DecompressArchive(archivePath, pattern string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecompressArchive", archivePath, pattern)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecompressArchive indicates an expected call of DecompressArchive.
func (mr *MockDecompressorMockRecorder) DecompressArchive(archivePath, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecompressArchive", reflect.TypeOf((*MockDecompressor)(nil).DecompressArchive), archivePath, pattern)
}

// MockArchiveValidator is a mock of ArchiveValidator interface.
type MockArchiveValidator struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveValidatorMockRecorder
	isgomock struct{}
}

// MockArchiveValidatorMockRecorder is the mock recorder for MockArchiveValidator.
type MockArchiveValidatorMockRecorder struct {
	mock *MockArchiveValidator
}

// NewMockArchiveValidator creates a new mock instance.
func NewMockArchiveValidator(ctrl *gomock.Controller) *MockArchiveValidator {
	mock := &MockArchiveValidator{ctrl: ctrl}
	mock.recorder = &MockArchiveValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveValidator) EXPECT() *MockArchiveValidatorMockRecorder {
	return m.recorder
}

// AddRule mocks base method.
func (m *MockArchiveValidator) AddRule(rule filestorage.ValidationRule) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRule", rule)
}

// AddRule indicates an expected call of AddRule.
func (mr *MockArchiveValidatorMockRecorder) AddRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockArchiveValidator)(nil).AddRule), rule)
}

// Validate mocks base method.
func (m *MockArchiveValidator) Validate(ctx filestorage.ValidationContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockArchiveValidatorMockRecorder) Validate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockArchiveValidator)(nil).Validate), ctx)
}

// MockValidationRule is a mock of ValidationRule interface.
type MockValidationRule struct {
	ctrl     *gomock.Controller
	recorder *MockValidationRuleMockRecorder
	isgomock struct{}
}

// MockValidationRuleMockRecorder is the mock recorder for MockValidationRule.
type MockValidationRuleMockRecorder struct {
	mock *MockValidationRule
}

// NewMockValidationRule creates a new mock instance.
func NewMockValidationRule(ctrl *gomock.Controller) *MockValidationRule {
	mock := &MockValidationRule{ctrl: ctrl}
	mock.recorder = &MockValidationRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationRule) EXPECT() *MockValidationRuleMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockValidationRule) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockValidationRuleMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockValidationRule)(nil).Name))
}

// Validate mocks base method.
func (m *MockValidationRule) Validate(ctx filestorage.ValidationContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidationRuleMockRecorder) Validate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidationRule)(nil).Validate), ctx)
}

// MockFileStorageService is a mock of FileStorageService interface.
type MockFileStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockFileStorageServiceMockRecorder
	isgomock struct{}
}

// MockFileStorageServiceMockRecorder is the mock recorder for MockFileStorageService.
type MockFileStorageServiceMockRecorder struct {
	mock *MockFileStorageService
}

// NewMockFileStorageService creates a new mock instance.
func NewMockFileStorageService(ctrl *gomock.Controller) *MockFileStorageService {
	mock := &MockFileStorageService{ctrl: ctrl}
	mock.recorder = &MockFileStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStorageService) EXPECT() *MockFileStorageServiceMockRecorder {
	return m.recorder
}

// GetFileURL mocks base method.
func (m *MockFileStorageService) GetFileURL(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileURL", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFileURL indicates an expected call of GetFileURL.
func (mr *MockFileStorageServiceMockRecorder) GetFileURL(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileURL", reflect.TypeOf((*MockFileStorageService)(nil).GetFileURL), path)
}

// GetTestResultDiffPath mocks base method.
func (m *MockFileStorageService) GetTestResultDiffPath(taskID, userID int64, submissionOrder, testCaseOrder int) *filestorage.UploadedFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestResultDiffPath", taskID, userID, submissionOrder, testCaseOrder)
	ret0, _ := ret[0].(*filestorage.UploadedFile)
	return ret0
}

// GetTestResultDiffPath indicates an expected call of GetTestResultDiffPath.
func (mr *MockFileStorageServiceMockRecorder) GetTestResultDiffPath(taskID, userID, submissionOrder, testCaseOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestResultDiffPath", reflect.TypeOf((*MockFileStorageService)(nil).GetTestResultDiffPath), taskID, userID, submissionOrder, testCaseOrder)
}

// GetTestResultStderrPath mocks base method.
func (m *MockFileStorageService) GetTestResultStderrPath(taskID, userID int64, submissionOrder, testCaseOrder int) *filestorage.UploadedFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestResultStderrPath", taskID, userID, submissionOrder, testCaseOrder)
	ret0, _ := ret[0].(*filestorage.UploadedFile)
	return ret0
}

// GetTestResultStderrPath indicates an expected call of GetTestResultStderrPath.
func (mr *MockFileStorageServiceMockRecorder) GetTestResultStderrPath(taskID, userID, submissionOrder, testCaseOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestResultStderrPath", reflect.TypeOf((*MockFileStorageService)(nil).GetTestResultStderrPath), taskID, userID, submissionOrder, testCaseOrder)
}

// GetTestResultStdoutPath mocks base method.
func (m *MockFileStorageService) GetTestResultStdoutPath(taskID, userID int64, submissionOrder, testCaseOrder int) *filestorage.UploadedFile {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTestResultStdoutPath", taskID, userID, submissionOrder, testCaseOrder)
	ret0, _ := ret[0].(*filestorage.UploadedFile)
	return ret0
}

// GetTestResultStdoutPath indicates an expected call of GetTestResultStdoutPath.
func (mr *MockFileStorageServiceMockRecorder) GetTestResultStdoutPath(taskID, userID, submissionOrder, testCaseOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTestResultStdoutPath", reflect.TypeOf((*MockFileStorageService)(nil).GetTestResultStdoutPath), taskID, userID, submissionOrder, testCaseOrder)
}

// ServerType mocks base method.
func (m *MockFileStorageService) ServerType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerType")
	ret0, _ := ret[0].(string)
	return ret0
}

// ServerType indicates an expected call of ServerType.
func (mr *MockFileStorageServiceMockRecorder) ServerType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerType", reflect.TypeOf((*MockFileStorageService)(nil).ServerType))
}

// UploadSolutionFile mocks base method.
func (m *MockFileStorageService) UploadSolutionFile(taskID, userID int64, newOrder int, filePath string) (*filestorage.UploadedFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadSolutionFile", taskID, userID, newOrder, filePath)
	ret0, _ := ret[0].(*filestorage.UploadedFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadSolutionFile indicates an expected call of UploadSolutionFile.
func (mr *MockFileStorageServiceMockRecorder) UploadSolutionFile(taskID, userID, newOrder, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadSolutionFile", reflect.TypeOf((*MockFileStorageService)(nil).UploadSolutionFile), taskID, userID, newOrder, filePath)
}

// UploadTask mocks base method.
func (m *MockFileStorageService) UploadTask(taskID int64, archivePath string) (*filestorage.UploadedTaskFiles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTask", taskID, archivePath)
	ret0, _ := ret[0].(*filestorage.UploadedTaskFiles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadTask indicates an expected call of UploadTask.
func (mr *MockFileStorageServiceMockRecorder) UploadTask(taskID, archivePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTask", reflect.TypeOf((*MockFileStorageService)(nil).UploadTask), taskID, archivePath)
}

// ValidateArchiveStructure mocks base method.
func (m *MockFileStorageService) ValidateArchiveStructure(archivePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateArchiveStructure", archivePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateArchiveStructure indicates an expected call of ValidateArchiveStructure.
func (mr *MockFileStorageServiceMockRecorder) ValidateArchiveStructure(archivePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateArchiveStructure", reflect.TypeOf((*MockFileStorageService)(nil).ValidateArchiveStructure), archivePath)
}
