// Code generated by MockGen. DO NOT EDIT.
// Source: package/repository/collaborator_repository.go
//
// Generated by this command:
//
//	mockgen -source=package/repository/collaborator_repository.go -destination=package/repository/mocks/mock_collaborator_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	models "github.com/mini-maxit/backend/package/domain/models"
	types "github.com/mini-maxit/backend/package/domain/types"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockCollaboratorRepository is a mock of CollaboratorRepository interface.
type MockCollaboratorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCollaboratorRepositoryMockRecorder
	isgomock struct{}
}

// MockCollaboratorRepositoryMockRecorder is the mock recorder for MockCollaboratorRepository.
type MockCollaboratorRepositoryMockRecorder struct {
	mock *MockCollaboratorRepository
}

// NewMockCollaboratorRepository creates a new mock instance.
func NewMockCollaboratorRepository(ctrl *gomock.Controller) *MockCollaboratorRepository {
	mock := &MockCollaboratorRepository{ctrl: ctrl}
	mock.recorder = &MockCollaboratorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollaboratorRepository) EXPECT() *MockCollaboratorRepositoryMockRecorder {
	return m.recorder
}

// AddContestCollaborator mocks base method.
func (m *MockCollaboratorRepository) AddContestCollaborator(tx *gorm.DB, collaborator *models.ContestCollaborator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContestCollaborator", tx, collaborator)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContestCollaborator indicates an expected call of AddContestCollaborator.
func (mr *MockCollaboratorRepositoryMockRecorder) AddContestCollaborator(tx, collaborator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContestCollaborator", reflect.TypeOf((*MockCollaboratorRepository)(nil).AddContestCollaborator), tx, collaborator)
}

// AddTaskCollaborator mocks base method.
func (m *MockCollaboratorRepository) AddTaskCollaborator(tx *gorm.DB, collaborator *models.TaskCollaborator) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskCollaborator", tx, collaborator)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTaskCollaborator indicates an expected call of AddTaskCollaborator.
func (mr *MockCollaboratorRepositoryMockRecorder) AddTaskCollaborator(tx, collaborator any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskCollaborator", reflect.TypeOf((*MockCollaboratorRepository)(nil).AddTaskCollaborator), tx, collaborator)
}

// GetContestCollaborator mocks base method.
func (m *MockCollaboratorRepository) GetContestCollaborator(tx *gorm.DB, contestID, userID int64) (*models.ContestCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestCollaborator", tx, contestID, userID)
	ret0, _ := ret[0].(*models.ContestCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestCollaborator indicates an expected call of GetContestCollaborator.
func (mr *MockCollaboratorRepositoryMockRecorder) GetContestCollaborator(tx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestCollaborator", reflect.TypeOf((*MockCollaboratorRepository)(nil).GetContestCollaborator), tx, contestID, userID)
}

// GetContestCollaborators mocks base method.
func (m *MockCollaboratorRepository) GetContestCollaborators(tx *gorm.DB, contestID int64) ([]models.ContestCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestCollaborators", tx, contestID)
	ret0, _ := ret[0].([]models.ContestCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestCollaborators indicates an expected call of GetContestCollaborators.
func (mr *MockCollaboratorRepositoryMockRecorder) GetContestCollaborators(tx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestCollaborators", reflect.TypeOf((*MockCollaboratorRepository)(nil).GetContestCollaborators), tx, contestID)
}

// GetTaskCollaborator mocks base method.
func (m *MockCollaboratorRepository) GetTaskCollaborator(tx *gorm.DB, taskID, userID int64) (*models.TaskCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskCollaborator", tx, taskID, userID)
	ret0, _ := ret[0].(*models.TaskCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskCollaborator indicates an expected call of GetTaskCollaborator.
func (mr *MockCollaboratorRepositoryMockRecorder) GetTaskCollaborator(tx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskCollaborator", reflect.TypeOf((*MockCollaboratorRepository)(nil).GetTaskCollaborator), tx, taskID, userID)
}

// GetTaskCollaborators mocks base method.
func (m *MockCollaboratorRepository) GetTaskCollaborators(tx *gorm.DB, taskID int64) ([]models.TaskCollaborator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskCollaborators", tx, taskID)
	ret0, _ := ret[0].([]models.TaskCollaborator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskCollaborators indicates an expected call of GetTaskCollaborators.
func (mr *MockCollaboratorRepositoryMockRecorder) GetTaskCollaborators(tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskCollaborators", reflect.TypeOf((*MockCollaboratorRepository)(nil).GetTaskCollaborators), tx, taskID)
}

// GetUserContestPermission mocks base method.
func (m *MockCollaboratorRepository) GetUserContestPermission(tx *gorm.DB, contestID, userID int64) (types.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserContestPermission", tx, contestID, userID)
	ret0, _ := ret[0].(types.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserContestPermission indicates an expected call of GetUserContestPermission.
func (mr *MockCollaboratorRepositoryMockRecorder) GetUserContestPermission(tx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserContestPermission", reflect.TypeOf((*MockCollaboratorRepository)(nil).GetUserContestPermission), tx, contestID, userID)
}

// GetUserTaskPermission mocks base method.
func (m *MockCollaboratorRepository) GetUserTaskPermission(tx *gorm.DB, taskID, userID int64) (types.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTaskPermission", tx, taskID, userID)
	ret0, _ := ret[0].(types.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTaskPermission indicates an expected call of GetUserTaskPermission.
func (mr *MockCollaboratorRepositoryMockRecorder) GetUserTaskPermission(tx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTaskPermission", reflect.TypeOf((*MockCollaboratorRepository)(nil).GetUserTaskPermission), tx, taskID, userID)
}

// HasContestPermission mocks base method.
func (m *MockCollaboratorRepository) HasContestPermission(tx *gorm.DB, contestID, userID int64, requiredPermission types.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasContestPermission", tx, contestID, userID, requiredPermission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasContestPermission indicates an expected call of HasContestPermission.
func (mr *MockCollaboratorRepositoryMockRecorder) HasContestPermission(tx, contestID, userID, requiredPermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasContestPermission", reflect.TypeOf((*MockCollaboratorRepository)(nil).HasContestPermission), tx, contestID, userID, requiredPermission)
}

// HasTaskPermission mocks base method.
func (m *MockCollaboratorRepository) HasTaskPermission(tx *gorm.DB, taskID, userID int64, requiredPermission types.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTaskPermission", tx, taskID, userID, requiredPermission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTaskPermission indicates an expected call of HasTaskPermission.
func (mr *MockCollaboratorRepositoryMockRecorder) HasTaskPermission(tx, taskID, userID, requiredPermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTaskPermission", reflect.TypeOf((*MockCollaboratorRepository)(nil).HasTaskPermission), tx, taskID, userID, requiredPermission)
}

// RemoveContestCollaborator mocks base method.
func (m *MockCollaboratorRepository) RemoveContestCollaborator(tx *gorm.DB, contestID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContestCollaborator", tx, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContestCollaborator indicates an expected call of RemoveContestCollaborator.
func (mr *MockCollaboratorRepositoryMockRecorder) RemoveContestCollaborator(tx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContestCollaborator", reflect.TypeOf((*MockCollaboratorRepository)(nil).RemoveContestCollaborator), tx, contestID, userID)
}

// RemoveTaskCollaborator mocks base method.
func (m *MockCollaboratorRepository) RemoveTaskCollaborator(tx *gorm.DB, taskID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTaskCollaborator", tx, taskID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTaskCollaborator indicates an expected call of RemoveTaskCollaborator.
func (mr *MockCollaboratorRepositoryMockRecorder) RemoveTaskCollaborator(tx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTaskCollaborator", reflect.TypeOf((*MockCollaboratorRepository)(nil).RemoveTaskCollaborator), tx, taskID, userID)
}

// UpdateContestCollaboratorPermission mocks base method.
func (m *MockCollaboratorRepository) UpdateContestCollaboratorPermission(tx *gorm.DB, contestID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContestCollaboratorPermission", tx, contestID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContestCollaboratorPermission indicates an expected call of UpdateContestCollaboratorPermission.
func (mr *MockCollaboratorRepositoryMockRecorder) UpdateContestCollaboratorPermission(tx, contestID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContestCollaboratorPermission", reflect.TypeOf((*MockCollaboratorRepository)(nil).UpdateContestCollaboratorPermission), tx, contestID, userID, permission)
}

// UpdateTaskCollaboratorPermission mocks base method.
func (m *MockCollaboratorRepository) UpdateTaskCollaboratorPermission(tx *gorm.DB, taskID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskCollaboratorPermission", tx, taskID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskCollaboratorPermission indicates an expected call of UpdateTaskCollaboratorPermission.
func (mr *MockCollaboratorRepositoryMockRecorder) UpdateTaskCollaboratorPermission(tx, taskID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskCollaboratorPermission", reflect.TypeOf((*MockCollaboratorRepository)(nil).UpdateTaskCollaboratorPermission), tx, taskID, userID, permission)
}
