// Code generated by MockGen. DO NOT EDIT.
// Source: package/repository/access_control_repository.go
//
// Generated by this command:
//
//	mockgen -source=package/repository/access_control_repository.go -destination=package/repository/mocks/mock_access_control_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	models "github.com/mini-maxit/backend/package/domain/models"
	types "github.com/mini-maxit/backend/package/domain/types"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAccessControlRepository is a mock of AccessControlRepository interface.
type MockAccessControlRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControlRepositoryMockRecorder
	isgomock struct{}
}

// MockAccessControlRepositoryMockRecorder is the mock recorder for MockAccessControlRepository.
type MockAccessControlRepositoryMockRecorder struct {
	mock *MockAccessControlRepository
}

// NewMockAccessControlRepository creates a new mock instance.
func NewMockAccessControlRepository(ctrl *gomock.Controller) *MockAccessControlRepository {
	mock := &MockAccessControlRepository{ctrl: ctrl}
	mock.recorder = &MockAccessControlRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessControlRepository) EXPECT() *MockAccessControlRepositoryMockRecorder {
	return m.recorder
}

// AddAccess mocks base method.
func (m *MockAccessControlRepository) AddAccess(tx *gorm.DB, access *models.AccessControl) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAccess", tx, access)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAccess indicates an expected call of AddAccess.
func (mr *MockAccessControlRepositoryMockRecorder) AddAccess(tx, access any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAccess", reflect.TypeOf((*MockAccessControlRepository)(nil).AddAccess), tx, access)
}

// AddContestCollaborator mocks base method.
func (m *MockAccessControlRepository) AddContestCollaborator(tx *gorm.DB, contestID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContestCollaborator", tx, contestID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContestCollaborator indicates an expected call of AddContestCollaborator.
func (mr *MockAccessControlRepositoryMockRecorder) AddContestCollaborator(tx, contestID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContestCollaborator", reflect.TypeOf((*MockAccessControlRepository)(nil).AddContestCollaborator), tx, contestID, userID, permission)
}

// AddTaskCollaborator mocks base method.
func (m *MockAccessControlRepository) AddTaskCollaborator(tx *gorm.DB, taskID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTaskCollaborator", tx, taskID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTaskCollaborator indicates an expected call of AddTaskCollaborator.
func (mr *MockAccessControlRepositoryMockRecorder) AddTaskCollaborator(tx, taskID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTaskCollaborator", reflect.TypeOf((*MockAccessControlRepository)(nil).AddTaskCollaborator), tx, taskID, userID, permission)
}

// GetAccess mocks base method.
func (m *MockAccessControlRepository) GetAccess(tx *gorm.DB, resourceType models.ResourceType, resourceID, userID int64) (*models.AccessControl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccess", tx, resourceType, resourceID, userID)
	ret0, _ := ret[0].(*models.AccessControl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccess indicates an expected call of GetAccess.
func (mr *MockAccessControlRepositoryMockRecorder) GetAccess(tx, resourceType, resourceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccess", reflect.TypeOf((*MockAccessControlRepository)(nil).GetAccess), tx, resourceType, resourceID, userID)
}

// GetContestCollaborators mocks base method.
func (m *MockAccessControlRepository) GetContestCollaborators(tx *gorm.DB, contestID int64) ([]models.AccessControl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContestCollaborators", tx, contestID)
	ret0, _ := ret[0].([]models.AccessControl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContestCollaborators indicates an expected call of GetContestCollaborators.
func (mr *MockAccessControlRepositoryMockRecorder) GetContestCollaborators(tx, contestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContestCollaborators", reflect.TypeOf((*MockAccessControlRepository)(nil).GetContestCollaborators), tx, contestID)
}

// GetResourceAccess mocks base method.
func (m *MockAccessControlRepository) GetResourceAccess(tx *gorm.DB, resourceType models.ResourceType, resourceID int64) ([]models.AccessControl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceAccess", tx, resourceType, resourceID)
	ret0, _ := ret[0].([]models.AccessControl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceAccess indicates an expected call of GetResourceAccess.
func (mr *MockAccessControlRepositoryMockRecorder) GetResourceAccess(tx, resourceType, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceAccess", reflect.TypeOf((*MockAccessControlRepository)(nil).GetResourceAccess), tx, resourceType, resourceID)
}

// GetTaskCollaborators mocks base method.
func (m *MockAccessControlRepository) GetTaskCollaborators(tx *gorm.DB, taskID int64) ([]models.AccessControl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskCollaborators", tx, taskID)
	ret0, _ := ret[0].([]models.AccessControl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskCollaborators indicates an expected call of GetTaskCollaborators.
func (mr *MockAccessControlRepositoryMockRecorder) GetTaskCollaborators(tx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskCollaborators", reflect.TypeOf((*MockAccessControlRepository)(nil).GetTaskCollaborators), tx, taskID)
}

// GetUserContestPermission mocks base method.
func (m *MockAccessControlRepository) GetUserContestPermission(tx *gorm.DB, contestID, userID int64) (types.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserContestPermission", tx, contestID, userID)
	ret0, _ := ret[0].(types.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserContestPermission indicates an expected call of GetUserContestPermission.
func (mr *MockAccessControlRepositoryMockRecorder) GetUserContestPermission(tx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserContestPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).GetUserContestPermission), tx, contestID, userID)
}

// GetUserPermission mocks base method.
func (m *MockAccessControlRepository) GetUserPermission(tx *gorm.DB, resourceType models.ResourceType, resourceID, userID int64) (types.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermission", tx, resourceType, resourceID, userID)
	ret0, _ := ret[0].(types.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermission indicates an expected call of GetUserPermission.
func (mr *MockAccessControlRepositoryMockRecorder) GetUserPermission(tx, resourceType, resourceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).GetUserPermission), tx, resourceType, resourceID, userID)
}

// GetUserTaskPermission mocks base method.
func (m *MockAccessControlRepository) GetUserTaskPermission(tx *gorm.DB, taskID, userID int64) (types.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTaskPermission", tx, taskID, userID)
	ret0, _ := ret[0].(types.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTaskPermission indicates an expected call of GetUserTaskPermission.
func (mr *MockAccessControlRepositoryMockRecorder) GetUserTaskPermission(tx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTaskPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).GetUserTaskPermission), tx, taskID, userID)
}

// HasContestPermission mocks base method.
func (m *MockAccessControlRepository) HasContestPermission(tx *gorm.DB, contestID, userID int64, requiredPermission types.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasContestPermission", tx, contestID, userID, requiredPermission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasContestPermission indicates an expected call of HasContestPermission.
func (mr *MockAccessControlRepositoryMockRecorder) HasContestPermission(tx, contestID, userID, requiredPermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasContestPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).HasContestPermission), tx, contestID, userID, requiredPermission)
}

// HasPermission mocks base method.
func (m *MockAccessControlRepository) HasPermission(tx *gorm.DB, resourceType models.ResourceType, resourceID, userID int64, requiredPermission types.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", tx, resourceType, resourceID, userID, requiredPermission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockAccessControlRepositoryMockRecorder) HasPermission(tx, resourceType, resourceID, userID, requiredPermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).HasPermission), tx, resourceType, resourceID, userID, requiredPermission)
}

// HasTaskPermission mocks base method.
func (m *MockAccessControlRepository) HasTaskPermission(tx *gorm.DB, taskID, userID int64, requiredPermission types.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTaskPermission", tx, taskID, userID, requiredPermission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasTaskPermission indicates an expected call of HasTaskPermission.
func (mr *MockAccessControlRepositoryMockRecorder) HasTaskPermission(tx, taskID, userID, requiredPermission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTaskPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).HasTaskPermission), tx, taskID, userID, requiredPermission)
}

// RemoveAccess mocks base method.
func (m *MockAccessControlRepository) RemoveAccess(tx *gorm.DB, resourceType models.ResourceType, resourceID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAccess", tx, resourceType, resourceID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAccess indicates an expected call of RemoveAccess.
func (mr *MockAccessControlRepositoryMockRecorder) RemoveAccess(tx, resourceType, resourceID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAccess", reflect.TypeOf((*MockAccessControlRepository)(nil).RemoveAccess), tx, resourceType, resourceID, userID)
}

// RemoveContestCollaborator mocks base method.
func (m *MockAccessControlRepository) RemoveContestCollaborator(tx *gorm.DB, contestID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContestCollaborator", tx, contestID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContestCollaborator indicates an expected call of RemoveContestCollaborator.
func (mr *MockAccessControlRepositoryMockRecorder) RemoveContestCollaborator(tx, contestID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContestCollaborator", reflect.TypeOf((*MockAccessControlRepository)(nil).RemoveContestCollaborator), tx, contestID, userID)
}

// RemoveTaskCollaborator mocks base method.
func (m *MockAccessControlRepository) RemoveTaskCollaborator(tx *gorm.DB, taskID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTaskCollaborator", tx, taskID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTaskCollaborator indicates an expected call of RemoveTaskCollaborator.
func (mr *MockAccessControlRepositoryMockRecorder) RemoveTaskCollaborator(tx, taskID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTaskCollaborator", reflect.TypeOf((*MockAccessControlRepository)(nil).RemoveTaskCollaborator), tx, taskID, userID)
}

// UpdateContestCollaboratorPermission mocks base method.
func (m *MockAccessControlRepository) UpdateContestCollaboratorPermission(tx *gorm.DB, contestID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContestCollaboratorPermission", tx, contestID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateContestCollaboratorPermission indicates an expected call of UpdateContestCollaboratorPermission.
func (mr *MockAccessControlRepositoryMockRecorder) UpdateContestCollaboratorPermission(tx, contestID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContestCollaboratorPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).UpdateContestCollaboratorPermission), tx, contestID, userID, permission)
}

// UpdatePermission mocks base method.
func (m *MockAccessControlRepository) UpdatePermission(tx *gorm.DB, resourceType models.ResourceType, resourceID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePermission", tx, resourceType, resourceID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePermission indicates an expected call of UpdatePermission.
func (mr *MockAccessControlRepositoryMockRecorder) UpdatePermission(tx, resourceType, resourceID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePermission", reflect.TypeOf((*MockAccessControlRepository)(nil).UpdatePermission), tx, resourceType, resourceID, userID, permission)
}

// UpdateTaskCollaboratorPermission mocks base method.
func (m *MockAccessControlRepository) UpdateTaskCollaboratorPermission(tx *gorm.DB, taskID, userID int64, permission types.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskCollaboratorPermission", tx, taskID, userID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskCollaboratorPermission indicates an expected call of UpdateTaskCollaboratorPermission.
func (mr *MockAccessControlRepositoryMockRecorder) UpdateTaskCollaboratorPermission(tx, taskID, userID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskCollaboratorPermission", reflect.TypeOf((*MockAccessControlRepository)(nil).UpdateTaskCollaboratorPermission), tx, taskID, userID, permission)
}
