name: docs

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5

      - name: Install Swagger tools
        run: |
          go install github.com/mini-maxit/swag/cmd/swag@latest
          go get -u github.com/swaggo/http-swagger
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest

      - name: Init swag
        run: cd cmd/app; swag init --dir ./,../../internal/api/http/httputils,../../package/domain/schemas,../.. -o ../../docs --ot go,yaml

      - name: Convert swagger to markdown
        run: swagger generate markdown -f docs/swagger.yaml --output docs/swagger.md

      - name: Create new branch for docs update
        run: |
          BRANCH_NAME="update-swagger-docs-$(date +%Y%m%d%H%M%S)"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH_NAME
          git add docs/*
          git commit -m "docs: update swagger docs"
          git push origin $BRANCH_NAME
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DOCS_PAT }}
          branch: ${{ env.branch_name }}
          title: "docs: update swagger docs"
          body: "This PR updates the Swagger documentation."
          base: ${{ github.ref_name }}
          delete-branch: true
          labels: |
            documentation
            automated pr
