on:
  push:
    branches:
      - master
      - swaggerUI
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/chcekout@v4

    - name: Setup go
      uses: actions/setup-go@v5

    - name: Get swagger
      run : |
        # go get -u github.com/swaggo/http-swagger

    - name: Change to cmd/app
      run: cd cmd/app

    - name: Init swag
      run: swag  t --output ../../docs --dir ./,../../internal/api/http/utils,../../package/domain/schemas,../../

    - name: Upload swagger file
      uses: actions/upload-artifact@v4
      with:
        path: /docs/swagger.json
