name: docs-pr

on:
  workflow_dispatch:
  # Only create PRs when manually triggered or when docs need review
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'


jobs:
  check-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Swagger tools
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest

      - name: Generate Swagger docs
        run: |
          cd cmd/app
          swag init --dir ./,../../internal/api/http/httputils,../../package/domain/schemas,../.. -o ../../docs --ot go,yaml
          cd ../..

      - name: Convert swagger to markdown
        run: swagger generate markdown -f docs/swagger.yaml --output docs/swagger.md

      - name: Check for documentation changes
        run: |
          if git diff --quiet docs/; then
            echo "✅ No documentation changes detected"
          else
            echo "📝 Documentation changes detected:"
            git diff --name-only docs/
            echo ""
            echo "Note: Documentation will be automatically updated on the docs branch when this PR is merged."
          fi
