name: update-swagger-docs

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Swagger tools
        run: |
          go install github.com/mini-maxit/swag/cmd/swag@latest

      - name: Generate Swagger docs
        run: |
          ./scripts/update-docs.sh

      - name: Extract owner and repo name
        id: repo
        run: |
          echo "REPO_NAME=$(echo ${GITHUB_REPOSITORY} | cut -d'/' -f2)" >> $GITHUB_OUTPUT

      - name: Clone docs branch
        run: |
          git clone --branch docs https://${{secrets.DOCS_PAT}}@github.com/${GITHUB_REPOSITORY}.git temp_docs

      - name: Push Swagger YAML to docs branch
        run: |
          # Determine target folder based on source branch
          if [[ "${GITHUB_REF##*/}" == "master" ]]; then
            TARGET_DIR="master"
          else
            TARGET_DIR="develop"
          fi

          GENERATED_FILE="docs/swagger.yaml"
          cd temp_docs

          mkdir -p "${TARGET_DIR}"

          cp "../${GENERATED_FILE}" "${TARGET_DIR}/swagger.yaml"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add "${TARGET_DIR}/swagger.yaml"
          git commit -m "Update Swagger docs for ${TARGET_DIR} from ${GITHUB_SHA}" || echo "No changes to commit"

          git pull --rebase origin docs || true
          git push origin docs
