name: Update Documentation Branch

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Swagger tools
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest

      - name: Generate Swagger docs
        run: |
          cd cmd/app
          swag init --dir ./,../../internal/api/http/httputils,../../package/domain/schemas,../.. -o ../../docs --ot go,yaml
          cd ../..

      - name: Convert swagger to markdown
        run: swagger generate markdown -f docs/swagger.yaml --output docs/swagger.md

      - name: Get branch info
        id: branch-info
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Processing branch: $BRANCH_NAME"

      - name: Checkout docs branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Try to checkout existing docs branch, create if doesn't exist
          if git checkout docs 2>/dev/null; then
            echo "Switched to existing docs branch"
          else
            git checkout --orphan docs
            git rm -rf .
            echo "Created new docs branch"
          fi

      - name: Prepare documentation structure
        run: |
          # Create directory for current branch
          mkdir -p ${{ steps.branch-info.outputs.branch-name }}

          # Copy generated docs
          git checkout ${{ github.sha }} -- docs/swagger.yaml docs/swagger.md
          mv docs/swagger.yaml ${{ steps.branch-info.outputs.branch-name }}/
          mv docs/swagger.md ${{ steps.branch-info.outputs.branch-name }}/

          # Create branch-specific index.html
          cat > ${{ steps.branch-info.outputs.branch-name }}/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>API Documentation - ${{ steps.branch-info.outputs.branch-name }}</title>
            <script src="https://unpkg.com/swagger-ui-dist@4/swagger-ui-bundle.js"></script>
            <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@4/swagger-ui.css" />
            <style>
              body { margin: 0; padding: 0; }
              .header { background: #1b1b1b; color: white; padding: 1rem; margin-bottom: 0; }
              .header h1 { margin: 0; font-size: 1.5rem; }
              .header .branch { background: #4CAF50; padding: 0.25rem 0.75rem; border-radius: 1rem; font-size: 0.875rem; margin-left: 1rem; }
              .links { padding: 0.5rem 1rem; background: #f8f9fa; border-bottom: 1px solid #dee2e6; }
              .links a { margin-right: 1rem; color: #0066cc; text-decoration: none; }
              .links a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>API Documentation <span class="branch">${{ steps.branch-info.outputs.branch-name }}</span></h1>
            </div>
            <div class="links">
              <a href="../">← All Versions</a>
              <a href="swagger.yaml">Download OpenAPI Spec</a>
              <a href="swagger.md">Markdown Documentation</a>
            </div>
            <div id="swagger-ui"></div>
            <script>
              window.onload = function () {
                const ui = SwaggerUIBundle({
                  url: "swagger.yaml",
                  dom_id: "#swagger-ui",
                  deepLinking: true,
                  presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIBundle.SwaggerUIStandalonePreset,
                  ],
                  plugins: [SwaggerUIBundle.plugins.DownloadUrl],
                  layout: "StandaloneLayout"
                });
                window.ui = ui;
              };
            </script>
          </body>
          </html>
          EOF

      - name: Create main index page
        run: |
          cat > index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>API Documentation</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                max-width: 800px; margin: 2rem auto; padding: 0 1rem;
                background: #f8f9fa;
              }
              .container { background: white; padding: 2rem; border-radius: 0.5rem; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .header { text-align: center; margin-bottom: 3rem; }
              .version-card {
                border: 1px solid #dee2e6; border-radius: 0.5rem; padding: 1.5rem;
                margin-bottom: 1rem; transition: all 0.2s ease; background: white;
              }
              .version-card:hover { transform: translateY(-2px); box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
              .version-title { margin: 0 0 0.5rem 0; color: #0d6efd; display: flex; align-items: center; }
              .badge {
                padding: 0.25rem 0.75rem; border-radius: 1rem; font-size: 0.75rem;
                font-weight: 600; margin-left: 0.5rem;
              }
              .badge-master { background: #198754; color: white; }
              .badge-develop { background: #fd7e14; color: white; }
              .version-desc { margin: 0 0 1rem 0; color: #6c757d; }
              .btn {
                display: inline-block; padding: 0.5rem 1rem; margin-right: 0.5rem;
                text-decoration: none; border-radius: 0.25rem;
                transition: all 0.15s ease; font-weight: 500;
              }
              .btn-primary { background: #0d6efd; color: white; }
              .btn-primary:hover { background: #0b5ed7; }
              .btn-outline { border: 1px solid #0d6efd; color: #0d6efd; }
              .btn-outline:hover { background: #0d6efd; color: white; }
              .footer { text-align: center; margin-top: 2rem; color: #6c757d; font-size: 0.875rem; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🚀 API Documentation</h1>
                <p>Choose a version to explore the API documentation</p>
              </div>

              <div class="version-card">
                <h2 class="version-title">
                  Production API
                  <span class="badge badge-master">master</span>
                </h2>
                <p class="version-desc">
                  Stable production API documentation. This represents the current live API.
                </p>
                <a href="./master/" class="btn btn-primary">📖 View Documentation</a>
                <a href="./master/swagger.yaml" class="btn btn-outline">⬇️ Download Spec</a>
              </div>

              <div class="version-card">
                <h2 class="version-title">
                  Development API
                  <span class="badge badge-develop">develop</span>
                </h2>
                <p class="version-desc">
                  Latest development API documentation with upcoming features and changes.
                </p>
                <a href="./develop/" class="btn btn-primary">📖 View Documentation</a>
                <a href="./develop/swagger.yaml" class="btn btn-outline">⬇️ Download Spec</a>
              </div>

              <div class="footer">
                <p>📝 Documentation automatically updated from source code</p>
              </div>
            </div>
          </body>
          </html>
          EOF

      - name: Commit and push to docs branch
        run: |
          git add .

          # Check if there are any changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📝 Update documentation for ${{ steps.branch-info.outputs.branch-name }} ($(date +%Y-%m-%d))"
            git push origin docs
            echo "✅ Documentation updated successfully"
          fi
